module.exports = {
  db: { d: 'block' },
  dib: { d: 'inline-block' },
  di: { d: 'inline' },
  f: { d: 'flex' },
  fw: { fw: 'wrap' },
  ais: { ai: 'flex-start' },
  aic: { ai: 'center' },
  aie: { ai: 'flex-end' },
  jcs: { jc: 'flex-start' },
  jcc: { jc: 'center' },
  jce: { jc: 'flex-end' },
  jca: { jc: 'space-around' },
  jcb: { jc: 'space-between' },
  rel: { position: 'relative' },
  abs: { position: 'absolute' },
  fix: { position: 'fixed' },
  top: { top: 0 },
  bottom: { bottom: 0 },
  left: { left: 0 },
  right: { right: 0 },
  cover: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0
  },
  w: { w: 1 },
  h: { h: 1 },
  tac: { ta: 'center' },
  tar: { ta: 'right' },
  taj: { ta: 'justify' }
}
